---
layout: cv
title: Nathan Jackson's CV
---
# Nathan Jackson

nrjacks02@byui.edu | 865.585.6887 | [linkedin.com/in/nrjacks](https://www.linkedin.com/in/nrjacks/)

## Education

__EDUCATION__
_Brigham Young University - Idaho_
- Anticipated: July 2027
- GPA: 3.98
- Student Accounting Society & Data Science Society
- Recipient of Academic Scholarship (5/5 Semesters)
- Minor: Computer Programming | Emphasis: Data Science

## EXPERIENCE

__Emergency Response Operator__
_Becklar Monitoring_
- Respond to 100+ emergency alerts per shift, ensuring swift coordination with local authorities
- Manage urgent calls with an average response time under 2 minutes, maintaining calm
communication while gathering critical details
- Maintain detailed logs and documentation for incidents, ensuring 100% compliance with industry
and company standards
- Collaborate with a 50-operator team to improve response protocols and service reliability

__Full-Time Volunteer Representative__
_The Church of Jesus Christ of Latter-day Saints_
- Managed a demanding schedule of teaching and service projects, regularly working 60+
hours/week
- Adapted quickly to new environments and communities in 3 countries while making meaningful
connections and navigating cultural differences
- Developed fluency in German and regularly engaged in 14+ weekly lessons, presentations, and
community service projects exclusively in German
- Taught and counseled 100+ individuals from diverse cultural backgrounds

## SKILLS
- Programming & Data: Python, SQL, ETL (Extract, Transform, Load)
- Data Visualization & Analysis: Tableau, Excel
- Tools & Productivity: Microsoft Office Suite (Word, Excel, PowerPoint, Outlook)

### Footer Last updated: July 2025